"""add new fields to link model

Revision ID: 01df30681f12
Revises: 2b98a44e9634
Create Date: 2026-05-15 15:11:50.895230

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '01df30681f12'
down_revision: Union[str, Sequence[str], None] = '2b98a44e9634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('link', sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('link', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('link', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('link', sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('link', sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('link', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.add_column('link', sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('link', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('link', sa.Column('saved_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('link', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('link', 'saved_date')
    op.drop_column('link', 'text')
    op.drop_column('link', 'data')
    op.drop_column('link', 'url')
    op.drop_column('link', 'referrer')
    op.drop_column('link', 'creator')
    op.drop_column('link', 'date')
    op.drop_column('link', 'type')
    op.drop_column('link', 'source_id')
    op.drop_column('link', 'source')
    # ### end Alembic commands ###
