"""add unique constraint to link model

Revision ID: 127066b177a0
Revises: 01df30681f12
Create Date: 2026-05-23 11:39:25.194937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '127066b177a0'
down_revision: Union[str, Sequence[str], None] = '01df30681f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_source_item', 'link', ['source', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_source_item', 'link', type_='unique')
    # ### end Alembic commands ###
