"""add format field to link

Revision ID: 5e5d45aee452
Revises: 127066b177a0
Create Date: 2026-05-24 15:37:30.654973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5e5d45aee452'
down_revision: Union[str, Sequence[str], None] = '127066b177a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'format')
    # ### end Alembic commands ###
